# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDatosinvalidosregistro():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_datos_invalidos_registro(self):

    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(909, 738)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("_____")
    self.driver.find_element(By.ID, "password").send_keys("12")
    self.driver.find_element(By.ID, "cpassword").send_keys("12")
    self.driver.find_element(By.NAME, "firstName").send_keys("\"\"")
    self.driver.find_element(By.NAME, "lastName").send_keys("##")
    self.driver.find_element(By.NAME, "address1").send_keys("!!")
    self.driver.find_element(By.NAME, "address2").send_keys("\"\"")
    self.driver.find_element(By.NAME, "zipcode").send_keys("##")
    self.driver.find_element(By.NAME, "city").send_keys("$$")
    self.driver.find_element(By.NAME, "state").send_keys("%%")
    self.driver.find_element(By.NAME, "country").send_keys("&&")
    self.driver.find_element(By.NAME, "phone").send_keys("//")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    registered = self.driver.find_element(By.TAG_NAME, "p").text
    assert 'Registered Successfully' in registered # Si el sistema permitió registrar datos inválidos, acá salta el error.
