# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPe16tc06():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pe16tc06(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1376, 754)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("diogenes2@testing.com")
    self.driver.find_element(By.ID, "password").send_keys("a")
    self.driver.find_element(By.ID, "cpassword").send_keys("a")
    self.driver.find_element(By.NAME, "firstName").send_keys("8$#\"_")
    self.driver.find_element(By.NAME, "address1").send_keys("......")
    self.driver.find_element(By.NAME, "lastName").click()
    self.driver.find_element(By.NAME, "lastName").send_keys("#\"$\"#$")
    self.driver.find_element(By.NAME, "address2").send_keys("_____")
    self.driver.find_element(By.NAME, "zipcode").send_keys("$43352#$\"")
    self.driver.find_element(By.NAME, "state").send_keys("#$#\"a")
    self.driver.find_element(By.NAME, "country").send_keys("Argentina")
    self.driver.find_element(By.NAME, "phone").send_keys("hi")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    self.driver.find_element(By.NAME, "email").send_keys("sample@example.com")
    self.driver.find_element(By.NAME, "password").send_keys("sample33")
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    registered = self.driver.find_element(By.TAG_NAME, 'p').text
    assert 'Failed to create an account: invalid data' in registered

