# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPe16tc02():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pe16tc02(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1376, 754)
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.NAME, "email").send_keys("diogenes@testing.com")
    self.driver.find_element(By.NAME, "password").send_keys("diogenespass1")
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("diogenes1@testing.com")
    self.driver.find_element(By.ID, "password").send_keys("diogenespass")
    self.driver.find_element(By.ID, "cpassword").send_keys("diogenespass")
    self.driver.find_element(By.NAME, "firstName").send_keys("Diogenes")
    self.driver.find_element(By.NAME, "lastName").send_keys("Elperro")
    self.driver.find_element(By.NAME, "address1").send_keys("AVENIDA SIEMPRE VIVA")
    self.driver.find_element(By.NAME, "address2").send_keys("123")
    self.driver.find_element(By.NAME, "zipcode").send_keys("1155")
    self.driver.find_element(By.NAME, "city").send_keys("Los Angeles")
    self.driver.find_element(By.NAME, "state").send_keys("California")
    self.driver.find_element(By.NAME, "country").send_keys("USA")
    self.driver.find_element(By.NAME, "phone").send_keys("1 394 482 324")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    registered = self.driver.find_element(By.TAG_NAME, 'p').text
    assert 'Registered Successfully' in registered
