# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPe16tc00():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pe16tc00(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(1376, 754)
    self.driver.find_element(By.LINK_TEXT, "Sign In").click()
    self.driver.find_element(By.LINK_TEXT, "Register here").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.NAME, "email").send_keys("sample@example.com")
    self.driver.find_element(By.ID, "password").send_keys("sample33")
    self.driver.find_element(By.ID, "cpassword").send_keys("sample33")
    self.driver.find_element(By.NAME, "firstName").send_keys("Sample")
    self.driver.find_element(By.NAME, "lastName").send_keys("Samplito")
    self.driver.find_element(By.NAME, "address1").send_keys("AVENIDIA SIEMPRE VIVA")
    self.driver.find_element(By.NAME, "address2").send_keys("123")
    self.driver.find_element(By.NAME, "zipcode").send_keys("4421")
    self.driver.find_element(By.NAME, "city").send_keys("Chicago")
    self.driver.find_element(By.NAME, "state").send_keys("Illinoise")
    self.driver.find_element(By.NAME, "country").send_keys("USA")
    self.driver.find_element(By.NAME, "state").click()
    self.driver.find_element(By.NAME, "state").send_keys("Illinois")
    self.driver.find_element(By.NAME, "country").click()
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.NAME, "phone").click()
    self.driver.find_element(By.NAME, "phone").send_keys("1 112 332 442")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(13) > input").click()
    self.driver.find_element(By.NAME, "email").send_keys("sample@example.com")
    self.driver.find_element(By.NAME, "password").send_keys("sample33")
    registered = self.driver.find_element(By.TAG_NAME, 'p').text
    assert 'There is a user with this email address. Please try signing in' in registered

